name: ExtDN M2 Mess Detector

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  phpmd:
    name: M2 Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-mess-detector@master
